import { Inter } from "next/font/google";

import AppHeader from "@/components/AppHeader";
import AppFooter from "@/components/AppFooter";
import LineWrap from "@/components/LineWrap/LineWrap";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="relative min-h-full" lang="en">
      <body className={`${inter.className} h-full`}>
        <AppHeader />
        <LineWrap />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
